export const GET_AUTH_USER_DATA = 'AUTH/GET_AUTH_USER_DATA'
export const SET_USER_DATA = 'AUTH/SET_USER_DATA'
export const GET_CAPTCHA_URL = 'AUTH/GET_CAPTCHA_URL'
export const GET_CAPTCHA_URL_SUCCESS = 'AUTH/GET_CAPTCHA_URL_SUCCESS'
export const LOGIN = 'AUTH/LOGIN'
export const LOGOUT = 'AUTH/LOGOUT'



export const ADD_POST = 'PROFILE/ADD_POST' 
export const DELETE_POST = 'PROFILE/DELETE_POST'
export const GET_USER_PROFILE = 'PROFILE/GET_USER_PROFILE'
export const SET_USER_PROFILE = 'PROFILE/SET_USER_PROFILE'
export const GET_STATUS = 'PROFILE/GET_STATUS'
export const SET_STATUS = 'PROFILE/SET_STATUS'
export const UPDATE_STATUS = 'PROFILE/UPDATE_STATUS'
export const SAVE_PHOTO = 'PROFILE/SAVE_PHOTO'
export const SAVE_PHOTO_SUCCESS = 'PROFILE/SAVE_PHOTO_SUCCESS'
export const SAVE_PROFILE = 'PROFILE/SAVE_PROFILE'


export const FOLLOW = 'USERS/FOLLOW'
export const FOLLOW_SUCCESS = 'USERS/FOLLOW_SUCCESS'
export const UNFOLLOW = 'USERS/UNFOLLOW'
export const UNFOLLOW_SUCCESS = 'USERS/UNFOLLOW_SUCCESS'
export const REQUEST_USERS = 'USERS/REQUEST_USERS'
export const SET_USERS = 'USERS/SET_USERS'
export const SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE'
export const SET_FILTER = 'USERS/SET_FILTER'
export const TOGGLE_IS_FETCHING = 'USERS/TOGGLE_IS_FETCHING'
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USERS/TOGGLE_IS_FOLLOWING_PROGRESS'
export const SET_TOTAL_USERS_COUNT = 'USERS/SET_TOTAL_USERS_COUNT'


export const INITIALIZE_APP = 'APP/INITIALIZE_APP'
export const INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS'
export const CHANGE_LANGUAGE = 'APP/CHANGE_LANGUAGE'
export const SET_LANGUAGE = 'APP/SET_LANGUAGE'

export const MESSAGES_RECEIVED = 'CHAT/MESSAGES_RECEIVED'
export const STATUS_CHANGED = 'CHAT/STATUS_CHANGED'
export const START_MESSAGES_LISTENING = 'CHAT/START_MESSAGES_LISTENING'
export const STOP_MESSAGES_LISTENING = 'CHAT/STOP_MESSAGES_LISTENING'
export const SEND_MESSAGE = 'CHAT/SEND_MESSAGE'



//* ERRORS =======================================================================================================================================

export const SET_USER_PROFILE_ERROR = 'PROFILE/SET_USER_PROFILE_ERROR' 
export const SET_USER_STATUS_ERROR = 'PROFILE/SET_USER_STATUS_ERROR' 
export const UPDATE_USER_STATUS_ERROR = 'PROFILE/UPDATE_USER_STATUS_ERROR' 
export const SAVE_PROFILE_ERROR = 'PROFILE/SAVE_PROFILE_ERROR' 
export const SAVE_PHOTO_ERROR = 'PROFILE/SAVE_PHOTO_ERROR' 
export const REQUEST_USERS_ERROR = 'USERS/REQUEST_USERS_ERROR' 
export const FOLLOW_ERROR = 'USERS/FOLLOW_ERROR' 
export const UNFOLLOW_ERROR = 'USERS/UNFOLLOW_ERROR' 
export const GET_AUTH_USER_DATA_ERROR = 'AUTH/GET_AUTH_USER_DATA_ERROR' 
export const GET_CAPTCHA_URL_ERROR = 'AUTH/GET_CAPTCHA_URL_ERROR' 
export const LOGIN_ERROR = 'AUTH/LOGIN_ERROR' 
export const LOGOUT_ERROR = 'AUTH/LOGOUT_ERROR' 
export const START_MESSAGES_LISTENING_ERROR = 'CHAT/START_MESSAGES_LISTENING_ERROR'
export const STOP_MESSAGES_LISTENING_ERROR = 'CHAT/STOP_MESSAGES_LISTENING_ERROR'
export const SEND_MESSAGE_ERROR = 'CHAT/SEND_MESSAGE_ERROR'
export const INITIALIZE_APP_ERROR = 'APP/INITIALIZE_APP_ERROR'
export const CHANGE_LANGUAGE_ERROR = 'APP/CHANGE_LANGUAGE_ERROR'

//* ERRORS =======================================================================================================================================