export const INITIALIZE_APP = 'APP/INITIALIZE_APP'
export const INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS'
export const CHANGE_LANGUAGE = 'APP/CHANGE_LANGUAGE'
export const SET_LANGUAGE = 'APP/SET_LANGUAGE'

export const INITIALIZE_APP_ERROR = 'APP/INITIALIZE_APP_ERROR'
export const CHANGE_LANGUAGE_ERROR = 'APP/CHANGE_LANGUAGE_ERROR'