export const FOLLOW = 'USERS/FOLLOW'
export const FOLLOW_SUCCESS = 'USERS/FOLLOW_SUCCESS'
export const UNFOLLOW = 'USERS/UNFOLLOW'
export const UNFOLLOW_SUCCESS = 'USERS/UNFOLLOW_SUCCESS'
export const REQUEST_USERS = 'USERS/REQUEST_USERS'
export const SET_USERS = 'USERS/SET_USERS'
export const SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE'
export const SET_FILTER = 'USERS/SET_FILTER'
export const TOGGLE_IS_FETCHING = 'USERS/TOGGLE_IS_FETCHING'
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USERS/TOGGLE_IS_FOLLOWING_PROGRESS'
export const SET_TOTAL_USERS_COUNT = 'USERS/SET_TOTAL_USERS_COUNT'



export const REQUEST_USERS_ERROR = 'USERS/REQUEST_USERS_ERROR' 
export const FOLLOW_ERROR = 'USERS/FOLLOW_ERROR' 
export const UNFOLLOW_ERROR = 'USERS/UNFOLLOW_ERROR' 