export const MESSAGES_RECEIVED = 'CHAT/MESSAGES_RECEIVED'
export const STATUS_CHANGED = 'CHAT/STATUS_CHANGED'
export const START_MESSAGES_LISTENING = 'CHAT/START_MESSAGES_LISTENING'
export const STOP_MESSAGES_LISTENING = 'CHAT/STOP_MESSAGES_LISTENING'
export const SEND_MESSAGE = 'CHAT/SEND_MESSAGE'


export const START_MESSAGES_LISTENING_ERROR = 'CHAT/START_MESSAGES_LISTENING_ERROR'
export const STOP_MESSAGES_LISTENING_ERROR = 'CHAT/STOP_MESSAGES_LISTENING_ERROR'
export const SEND_MESSAGE_ERROR = 'CHAT/SEND_MESSAGE_ERROR'